version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data: 